datasets:
  pope_vqa_eval:
    data_type: images
    build_info:
      annotation:
        random: /mnt/lustre/hanxiao/dpo_work/data/coco_pope_random.json
        popular: /mnt/lustre/hanxiao/dpo_work/data/coco_pope_popular.json
        adversarial: /mnt/lustre/hanxiao/dpo_work/data/coco_pope_adversarial.json
      images: /mnt/petrelfs/share_data/zhaozhiyuan/InstructBLIP/COCO_2014/process/images/val2014