datasets:
  instruct_blip_coco2017_vqga_test:
    data_type: images
    build_info:
      annotation: /mnt/petrelfs/hanxiao/working/all_coco_images.json
      image_ids: /mnt/petrelfs/hanxiao/working/coco_filter_ids.json
      images: /mnt/petrelfs/share_data/zhaozhiyuan/InstructBLIP/COCO2017/