datasets:
  formula_rec_eval:
    data_type: images
    build_info:
      images: /mnt/lustre/hanxiao/ocr-work/OCR-Data/dataset/data/pdf/val
      annotation: /mnt/lustre/hanxiao/ocr-work/OCR-Data/dataset/data/pdf/pdfmath.txt