datasets:
  formula_rec_train:
    data_type: images
    build_info:
      images: /mnt/lustre/hanxiao/ocr-work/OCR-Data/dataset/data/pdf/train
      annotation: /mnt/lustre/hanxiao/ocr-work/OCR-Data/dataset/data/pdf/pdfmath.txt